insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-01','Notebook', 'Descripcion',134000, 12,'notebook.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-02','Celular', 'Descripcion',80000, 14,'celular.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-03','Monitor LCD', 'Descripcion',60000, 20,'monitor_lcd.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-04','Escritorio', 'Descripcion',123000, 7,'escritorio.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-05','Arduino R3', 'Descripcion',8000, 15,'arduino_r3.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-06','Bicicleta Aro 29', 'Descripcion',200000, 10,'bicicleta_aro_29.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-07','Comedor + 6 sillas', 'Descripcion',230100, 5,'comedor_sillas.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-08','Cocina a Gas', 'Descripcion',130400, 7,'cocina_gas.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-09','Televisor 42"', 'Descripcion',180000, 12,'televisor_42.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-10','PlayStation 5', 'Descripcion',300000, 3,'playstation_5.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-11','Teclado', 'Descripcion',13400, 25,'teclado.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-12','Mouse', 'Descripcion',1400, 20,'mouse.png');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-13','Cama 2 Plazas', 'Descripcion',410000, 2,'cama_2_plazas.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-14','Refrigerador', 'Descripcion',150000, 12,'refrigerador.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-15','Silla Gamer con Luces', 'Descripcion',120000, 7,'silla_gamer.jpg');
insert into producto(codigo,nombre, descripcion,precio, stock,foto) values('PR-16','Lampara', 'Descripcion',13400, 12,'lampara.jpg');